In [1]:
print("hello world")

hello world


In [2]:
2+3


5

In [3]:
type(5)

int

In [4]:
first='abhishek'
last='agrahari'

In [5]:
print("my name is {} and last {}".format(first,last))

my name is abhishek and last agrahari


In [6]:
lst=[1,3,4,5,"Abhishek"]

In [7]:
type(lst)

list

In [8]:
lst.clear()

In [9]:
lst

[]

In [10]:
lst.copy()

[]

In [11]:
lst

[]

In [12]:
lst=[1,2,3,5,65,"Abhishek"]

In [13]:
lst.insert(5,"agrahari")

In [14]:
lst

[1, 2, 3, 5, 65, 'agrahari', 'Abhishek']

In [15]:
lst.append("kumar")

In [16]:
lst

[1, 2, 3, 5, 65, 'agrahari', 'Abhishek', 'kumar']

In [17]:
lst.extend([8,9])

In [18]:
lst

[1, 2, 3, 5, 65, 'agrahari', 'Abhishek', 'kumar', 8, 9]

In [19]:
lst.pop(3)

5

In [20]:
lst

[1, 2, 3, 65, 'agrahari', 'Abhishek', 'kumar', 8, 9]

In [21]:
lst.remove(2)

In [22]:
lst

[1, 3, 65, 'agrahari', 'Abhishek', 'kumar', 8, 9]

In [23]:
kst=[1,3,5,3,4,65,7]

In [24]:
kst.sort()

In [25]:
kst

[1, 3, 3, 4, 5, 7, 65]

In [26]:
kst.reverse()

In [27]:
kst

[65, 7, 5, 4, 3, 3, 1]

In [28]:
set ={1,2,3,4,5,6}

In [29]:
set

{1, 2, 3, 4, 5, 6}

In [30]:
set={1,2,32,34,4,3,2}

In [31]:
set

{1, 2, 3, 4, 32, 34}

In [32]:
set={2,3,3,3,34,5,4,2}

In [33]:
set

{2, 3, 4, 5, 34}

In [34]:
set.add("abhishek")

In [35]:
set

{2, 3, 34, 4, 5, 'abhishek'}

In [45]:
import numpy as np

In [46]:
arr=[1,2,3,4,5,6,7]

In [47]:
arr

[1, 2, 3, 4, 5, 6, 7]

In [48]:
type(arr)

list

In [49]:
testing=np.array(arr)

In [52]:
type(testing)

numpy.ndarray

In [53]:
testing.shape

(7,)

In [54]:
arr2=[2,4,54,6,7,6,6]
arr3=[4,6,7,87,8,8,87]

In [55]:
final=np.array([arr,arr2,arr3])
final

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4, 54,  6,  7,  6,  6],
       [ 4,  6,  7, 87,  8,  8, 87]])

In [57]:
final.shape

(3, 7)

In [58]:
final.reshape(7,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  2,  4],
       [54,  6,  7],
       [ 6,  6,  4],
       [ 6,  7, 87],
       [ 8,  8, 87]])

In [62]:
final[2:3,1:]

array([[ 6,  7, 87,  8,  8, 87]])

In [63]:
final[final<5]

array([1, 2, 3, 4, 2, 4, 4])

In [68]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [72]:
np.random.rand(3,3)

array([[0.50731182, 0.42333763, 0.21428199],
       [0.67606096, 0.50727187, 0.20878189],
       [0.52333215, 0.08851334, 0.13144774]])

In [73]:
import pandas as pd

In [79]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4'])

In [80]:
df

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [87]:
df.head(5)

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [89]:
df.to_csv('my.csc')

In [95]:
df.loc['R1']

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32

In [96]:
type(df.loc['R1'])

pandas.core.series.Series

In [97]:
df.isnull()

C1     C2     C3     C4
R1  False  False  False  False
R2  False  False  False  False
R3  False  False  False  False
R4  False  False  False  False
R5  False  False  False  False

In [98]:
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [101]:
df['C1'].unique()

array([ 0,  4,  8, 12, 16])

In [1]:
5!=6

True